openapi: 3.0.0
info:
  title: Payroll
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /wallet/v1/execute:
    post:
      tags:
        - default
      summary: TopupWithdrawal
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                amount: 200
                user_id: 100
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: 200 Topup
                  value:
                    wallet_transaction_id: 21
                    amount: 200
                    user_id: 1
        400:
          description: 400 errors
          content:
            application/json:
              schema:
                type: object
              examples:
                example-1:
                  summary: 400 Error Bad Request
                  value:
                    code: INVALID_BODY
                    message: The amount value must not be null
                example-2:
                  summary: 400 User Not found
                  value:
                    code: INVALID_USER
                    message: User id 100 not found
                example-3:
                  summary: 400 Insufficient Funds
                  value:
                    code: INVALID_BODY
                    message: The id wallet 1 has insufficient funds
  /wallet/v1/balance:
    get:
      tags:
        - default
      summary: Balance
      parameters:
        - name: user_id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: 200 Balance
                  value:
                    user_id: 1
                    balance: 300
        500:
          description: 500 error
          content:
            application/json:
              schema:
                type: object
                example:
                  example-1:
                    summary: 500 Balance
                    value:
                      code: GENERAL_ERROR
                      message: >-
                        Required request parameter 'user_id' for method parameter
                        type Long is not present
  /api/v1/payments:
    post:
      tags:
        - default
      summary: CreatePayment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                source:
                  type: COMPANY
                  sourceInformation:
                    name: ONTOP INC
                  account:
                    accountNumber: '0245253419'
                    currency: USD
                    routingNumber: '028444018'
                destination:
                  name: John Doe
                  userId: 1
                  account:
                    accountNumber: '5344543'
                    currency: USD
                    routingNumber: '123456789'
                amount: 100
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: 200 Create Payment
                  value:
                    requestInfo:
                      status: Processing
                    paymentInfo:
                      amount: 100
                      id: 9b17496b-22c0-4a8d-88a1-265316d1271d
        400:
          description: 400 errors
          content:
            application/json:
              schema:
                type: object
              examples:
                example-1:
                  summary: 400 Bad Request
                  value:
                    error: body is invalid, check postman collection example
        500:
          description: 400 errors
          content:
            application/json:
              schema:
                type: object
              examples:
                example-2:
                  summary: 500 PENDING
                  value:
                    code: GENERAL_ERROR
                    message: Destination information not valid
  /api/v1/payments/{paymentId}/status:
    get:
      tags:
        - default
      summary: GetPayment
      parameters:
        - name: paymentId
          in: path
          schema:
            type: string
          required: true
          example: 673ad390-2ef9-45e9-a696-ad225b61028d
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: Completed
                  value:
                    status: Completed
                    date: 03/23/2023 18:51:52
                example-1:
                  summary: Failed
                  value:
                    status: Failed
                    date: 03/23/2023 16:51:52
                example-2:
                  summary: Processing
                  value:
                    status: Processing
                    date: 03/23/2023 14:51:52